name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publishing ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --locked --release

      - name: Package
        shell: bash
        run: |
          cd target/release
          case ${{ matrix.os }} in
          windows-latest)
            7z -y a bacon-${{ matrix.os }}.zip bacon.exe
            sha256sum bacon-${{ matrix.os }}.zip > bacon-${{ matrix.os }}.sha256
            ;;
          *)
          tar czvf bacon-${{ matrix.os }}.tar.gz bacon
          shasum -a 256 bacon-${{ matrix.os }}.tar.gz > bacon-${{ matrix.os }}.sha256
            ;;
          esac;

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/bacon-*
